apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernet-demo-service
spec:
  selector:
    app: springboot-kubernet-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort   # expose externally for testing