apiVersion: v1
kind: Service
metadata:
  name: product-provider-service
spec:
  selector:
    app: product-provider
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort   # expose externally for testing